// Generated by gencpp from file scara_robot_control/find_end_vel.msg
// DO NOT EDIT!


#ifndef SCARA_ROBOT_CONTROL_MESSAGE_FIND_END_VEL_H
#define SCARA_ROBOT_CONTROL_MESSAGE_FIND_END_VEL_H

#include <ros/service_traits.h>


#include <scara_robot_control/find_end_velRequest.h>
#include <scara_robot_control/find_end_velResponse.h>


namespace scara_robot_control
{

struct find_end_vel
{

typedef find_end_velRequest Request;
typedef find_end_velResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct find_end_vel
} // namespace scara_robot_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::scara_robot_control::find_end_vel > {
  static const char* value()
  {
    return "9503a353c3cb5de32c444326819cd306";
  }

  static const char* value(const ::scara_robot_control::find_end_vel&) { return value(); }
};

template<>
struct DataType< ::scara_robot_control::find_end_vel > {
  static const char* value()
  {
    return "scara_robot_control/find_end_vel";
  }

  static const char* value(const ::scara_robot_control::find_end_vel&) { return value(); }
};


// service_traits::MD5Sum< ::scara_robot_control::find_end_velRequest> should match
// service_traits::MD5Sum< ::scara_robot_control::find_end_vel >
template<>
struct MD5Sum< ::scara_robot_control::find_end_velRequest>
{
  static const char* value()
  {
    return MD5Sum< ::scara_robot_control::find_end_vel >::value();
  }
  static const char* value(const ::scara_robot_control::find_end_velRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::scara_robot_control::find_end_velRequest> should match
// service_traits::DataType< ::scara_robot_control::find_end_vel >
template<>
struct DataType< ::scara_robot_control::find_end_velRequest>
{
  static const char* value()
  {
    return DataType< ::scara_robot_control::find_end_vel >::value();
  }
  static const char* value(const ::scara_robot_control::find_end_velRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::scara_robot_control::find_end_velResponse> should match
// service_traits::MD5Sum< ::scara_robot_control::find_end_vel >
template<>
struct MD5Sum< ::scara_robot_control::find_end_velResponse>
{
  static const char* value()
  {
    return MD5Sum< ::scara_robot_control::find_end_vel >::value();
  }
  static const char* value(const ::scara_robot_control::find_end_velResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::scara_robot_control::find_end_velResponse> should match
// service_traits::DataType< ::scara_robot_control::find_end_vel >
template<>
struct DataType< ::scara_robot_control::find_end_velResponse>
{
  static const char* value()
  {
    return DataType< ::scara_robot_control::find_end_vel >::value();
  }
  static const char* value(const ::scara_robot_control::find_end_velResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SCARA_ROBOT_CONTROL_MESSAGE_FIND_END_VEL_H
